version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NGINX_SSL_CN=${NGINX_SSL_CN}
    environment:
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - "443:443"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - frontend
    hostname: frontend

networks:
  frontend:
    driver: bridge
