version: '3.8'

services:
  apigateway:
    container_name: apigateway
    build: .
    environment:
      - SECRET_KEY=${ApiGateway_SECRET_KEY}
      - DEBUG=${ApiGateway_DEBUG}
      - FRONTEND_URL=https://51.21.250.243
      - ALLOWED_HOSTS=apigateway,51.21.250.243,192.168.1.86,192.168.1.111
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
    hostname: apigateway

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
