name: Deploy microservices

on:
  push:
    branches:
      - apigateway/microservices_Jaiye

jobs:
  scan-backend:
    name: Trivy Scan - Backend Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Scan all backend services with Trivy
        run: |
          for dir in backend/*; do
            if [ -f "$dir/Dockerfile" ]; then
